### ISSUE TITLE
Is this supported?

### ISSUE THREAD

**Issue by mtiller** [cloudflare/helm-charts#26]
Reading the Cloudflare docs, it seems like this is no longer supported.  If so, you should put something in the README to state this clearly.  It appears like Cloudflare offers no support for connecting Kubernetes clusters (apart from docs).  Is this correct?  If so, why?  Seems like a major use case?

**Comment by holms** [comment]
There's a new chart in here: https://github.com/cloudflare/argo-tunnel-examples/tree/master/helm/cloudflare-tunnel it's scattered all over the place.

@mattalberts by any chance can we have this new chart added in this official cloudflare helm-chart repo? Because currently there's absolutely no way to access it properly. Ther'es no .tgz version also available, so it's not functional for using with helm for now. 

https://github.com/cloudflare/argo-tunnel-examples/issues/26

**Comment by NJannasch** [comment]
Any update here on the restructuring?

**Comment by obezuk** [comment]
This chart has been merged into this repository.
